#!/bin/env zsh

# Load profile
for file in "/etc/profile" "$HOME/.profile" "/etc/xprofile" "$HOME/.config/X11/xprofile"
do
    if [ -f "$file" ]
    then
        echo "Loading profile from $file";
        . "$file"
    fi
done

# Load resources
for file in "/etc/X11/Xresources" "$HOME/.config/X11/Xresources"
do
    if [ -f "$file" ]
    then
        echo "Loading resource: $file"
        xrdb -merge "$file"
    fi
done

# Run all system xinitrc shell scripts
xinitdir="/etc/X11/xinit/xinitrc.d"
if [ -d "$xinitdir" ]
then
    for script in $xinitdir/*
    do
        echo "Loading xinit script $script"
        if [ -x "$script" -a ! -d "$script" ]
        then
            . "$script"
        fi
    done
fi

# set screen layout
~/.screenlayout/display.sh

# run picom
picom -b --experimental-backends

# set wallpapers
~/.fehbg

# start dunst notification daemon
systemctl start --user dunst

# start conky
#run conky --daemonize --pause=1

# start power manager
xfce4-power-manager 1> /dev/null 2>&1 &

# set screen locker
xss-lock -- betterlockscreen -l &

# start herbstluftwm. The --locked option eliminates flickering while wm starts
exec herbstluftwm --locked 

