#!/bin/env zsh

# Load resources
for file in "/etc/X11/Xresources" "$HOME/.config/X11/Xresources"
do
    if [ -f "$file" ]
    then
        echo "Loading resource: $file"
        xrdb -merge "$file"
    fi
done

# Run all system xinitrc shell scripts
xinitdir="/etc/X11/xinit/xinitrc.d"
if [ -d "$xinitdir" ]
then
    for script in $xinitdir/*
    do
        echo "Loading xinit script $script"
        if [ -x "$script" -a ! -d "$script" ]
        then
            . "$script"
        fi
    done
fi

# start authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# set compose key to Left_Alt
setxkbmap -option compose:ralt

# start clipboard history manager
greenclip daemon &

# set numlock
numlockx &

# set screen layout
~/.screenlayout/display.sh

# run picom
picom -b --experimental-backends

# set wallpapers
~/.fehbg

# start dunst notification daemon
systemctl start --user dunst

# start conky
#run conky --daemonize --pause=1

# start power manager
xfce4-power-manager 1> /dev/null 2>&1 &

# set screen locker
xss-lock -- betterlockscreen -l &

# start powerline-daemon (only needed if running powerline prompt in shell)
# powerline-daemon -q

# start gnome keyring daemon
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# start synology-drive
synology-drive &

# start herbstluftwm. The --locked option eliminates flickering while wm starts
exec herbstluftwm --locked 
#exec dbus-launch leftwm
