#!/bin/bash
# 2021-05-01 Moved dunst to ~/.config/herbstluftwm/autostart: font too big otherwise
# 2021-10-15 Move application bindings to ~/.config/herbstluftwm/autostart
# 2021-11-11 Move xfce4-power-manager to ~/.config/herbstluftwm/autostart. The power manager tries to call
#            the notification service which will not have started yet. This leads to dunst core dumps.

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# set compose key to Left_Alt
setxkbmap -option compose:ralt

# start clipboard history manager
greenclip daemon &

# set numlock
numlockx &

