#!/bin/zsh

setopt localoptions

_sinks=$(pactl list short sinks)

_lines=$(echo ${_sinks} | wc -l)

chosen=$(echo ${_sinks} | awk '{ print $1,$2,$7 }' | \
    rofi \
    -dmenu \
    -i \
    -xoffset -6 \
    -yoffset 30 \
    -p "🎜 🎚 Select Sink" \
    -theme-str "entry {enabled: false;} window {width: 37%; location: north east;} listview {lines: ${_lines};}" )

typeset -A sink
sink=( $( echo $chosen | awk '{ print "id",$1,"nm",$2 }' ) )

if [[ ! -z $sink[nm] ]]; then
    pactl set-default-sink $sink[nm]
    typeset -a inputs=( $(pactl list sink-inputs short | cut -f 1) )
    for input ( $inputs ); do pactl move-sink-input $input $sink[id]; done
fi

